// =======================================================
// This file is auto generated by [DataGenerator for Excel Lite] convertor,
// do not edit by youself!
// >>>> by HuMinghua <<<<  12 Apr 2020 00.03.47
// ======================================================


import Foundation


private let AUTO_PLIST_DATAEXPLORERS_PATH = Bundle.main.path(forResource: "DataExplorers", ofType: "plist")

private let AUTO_PLIST_DATAEXPLORERS_INDEX_NAME = 0   // 
private let AUTO_PLIST_DATAEXPLORERS_INDEX_GRADE = 1   // 
private let AUTO_PLIST_DATAEXPLORERS_INDEX_SHIFT = 2   // 
private let AUTO_PLIST_DATAEXPLORERS_INDEX_ROLE = 3   // 
private let AUTO_PLIST_DATAEXPLORERS_INDEX_NICKNAME = 4   // 
private let AUTO_PLIST_DATAEXPLORERS_INDEX_PHOTO = 5   // 
private let AUTO_PLIST_DATAEXPLORERS_INDEX_WANTLEARN = 6   // 
private let AUTO_PLIST_DATAEXPLORERS_INDEX_CANHEL = 7   // 
private let AUTO_PLIST_DATAEXPLORERS_INDEX_CONTACT = 8   // 


class ExplorerManager {

    public static let sharedManager = ExplorerManager()
    private init(){}

    private var _dataExplorerss = [DataExplorers]()

    func allDataExplorerss() -> [DataExplorers]{

        if _dataExplorerss.count > 0 {
            return _dataExplorerss
        }

        if let allDatas = NSArray(contentsOfFile: AUTO_PLIST_DATAEXPLORERS_PATH!) {

            for array in allDatas {
                guard let array = array as? [AnyObject] else {continue}

                let dataExplorers = DataExplorers()
                dataExplorers.name = array[AUTO_PLIST_DATAEXPLORERS_INDEX_NAME] as? String // 
                dataExplorers.grade = array[AUTO_PLIST_DATAEXPLORERS_INDEX_GRADE] as? String // 
                dataExplorers.shift = array[AUTO_PLIST_DATAEXPLORERS_INDEX_SHIFT] as? String // 
                dataExplorers.role = array[AUTO_PLIST_DATAEXPLORERS_INDEX_ROLE] as? String // 
                dataExplorers.nickname = array[AUTO_PLIST_DATAEXPLORERS_INDEX_NICKNAME] as? String // 
                dataExplorers.photo = array[AUTO_PLIST_DATAEXPLORERS_INDEX_PHOTO] as? String // 
                dataExplorers.wantLearn = array[AUTO_PLIST_DATAEXPLORERS_INDEX_WANTLEARN] as? String // 
                dataExplorers.canHelp = array[AUTO_PLIST_DATAEXPLORERS_INDEX_CANHEL] as? String // 
                dataExplorers.contact = array[AUTO_PLIST_DATAEXPLORERS_INDEX_CONTACT] as? String // 
                _dataExplorerss.append(dataExplorers)
            }
        }
        return _dataExplorerss
    }
}
