// =======================================================
// This file is auto generated by [DataGenerator for Excel Lite] convertor,
// do not edit by youself!
// >>>> by HuMinghua <<<<  12 Apr 2020 00.03.47
// ======================================================


import Foundation


class DataExplorers {
    var name : String? = nil; // 
    var grade : String? = nil; // 
    var shift : String? = nil; // 
    var role : String? = nil; // 
    var nickname : String? = nil; // 
    var photo : String? = nil; // 
    var wantLearn : String? = nil; // 
    var canHelp : String? = nil; // 
    var contact : String? = nil; // 
}
